env:
  global:
  - NODE_VERSION=stable

language: node_js
node_js: lts/*
before_install:
  - npm install -g npm@latest
  - npm install
  - npm install jest-expo
  - npm install -g expo-cli

script:
  - npm ci
  - npx expo login -u $indrareactnative -p $qawsedrf12345
  - npx expo publish --non-interactive
  - make test