env:
  global:
  - NODE_VERSION=stable

language: node_js
node_js: lts/*
before_install:
  - npm install -g yarn
  - npm install -g expo-cli@2.2.0
  - expo login -u $indrareactnative -p $qawsedrf12345
cache:
  yarn: true
install:
  - yarn install
script:
  - expo publish --release-channel $TRAVIS_PULL_REQUEST
  - make test